name: Emscripten
on: [push]
jobs:
  build_emscripten:
    container: conanio/gcc11-ubuntu16.04:1.39.0 # your docker image
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: conan --version
      - run: echo "🍏 This job's status is ${{ job.status }}."
