name: Emscripten
on: [push]
jobs:
  build_emscripten:
    runs-on: ubuntu-latest
    container: conanio/gcc11-ubuntu16.04:1.39.0 # your docker image
    env:
      CONAN_USER_HOME: /home/conan
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Configure Conan
        run: |
          conan config set general.revisions_enabled=1
          conan --version
      - name: Prepare deps
        run: |
          conan export .conan/recipes/magnum/all/conanfile.py magnum/2020.06@
          mkdir cmake-build-emsdk && cd cmake-build-emsdk
          conan lock create --profile:host=../.conan/profiles/emsdk --profile:build=default --lockfile=../lockfile.json --lockfile-out=lockfile.json --name=viewer --version=0.1 ../conanfile.txt --build --update
      - run: echo "🍏 This job's status is ${{ job.status }}."
