name: Emscripten
on: [push]
jobs:
  build_emscripten:
    runs-on: ubuntu-latest
    container: 
      image: conanio/gcc11-ubuntu16.04:1.41.0
    env:
      CONAN_USER_HOME: /home/conan
    steps:
      - name: Check out repository code
        # uses: actions/checkout@v2
        working-directory: /home/conan
        run: |
          git clone https://github.com/${{ github.repository }}.git
          cd ${{ github.event.repository.name }}
          git checkout ${{ github.ref }}

      - name: Cache Conan packages
        uses: actions/cache@v2
        with:
          key: conan-cache
          path: /home/conan/.conan

      - name: Configure Conan
        run: |
          conan config set general.revisions_enabled=1
          conan config install https://github.com/conan-io/conanclientcert.git
          conan --version

      - name: Prepare deps
        working-directory: /home/conan/${{ github.event.repository.name }}
        run: |
          cp .conan/settings.yml /home/conan/.conan/settings.yml
          conan export .conan/recipes/magnum/all/conanfile.py magnum/2020.06@
          conan export .conan/recipes/libjpeg/all/conanfile.py libjpeg/9d@
          mkdir cmake-build-emsdk

      - name: Build dependencies
        working-directory: /home/conan/${{ github.event.repository.name }}/cmake-build-emsdk
        run: |
          conan lock create --profile:host=../.conan/profiles/emsdk --profile:build=default --lockfile=../lockfile.json --lockfile-out=lockfile.json --name=viewer --version=0.1 ../conanfile.txt --build --update
          conan install --lockfile=lockfile.json ../conanfile.txt --build=missing --generator=virtualenv
          conan remove "*" --builds --force
          conan remove "*" --src --force

      - name: Build the project
        working-directory: /home/conan/${{ github.event.repository.name }}/cmake-build-emsdk
        run: |
          pwd
          ls -la
          . /home/conan/${{ github.event.repository.name }}/cmake-build-emsdk/activate.sh
          cmake .. -DCMAKE_MODULE_PATH=$(pwd) -DCMAKE_TOOLCHAIN_FILE=$CONAN_CMAKE_TOOLCHAIN_FILE
          make

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: /home/conan/${{ github.event.repository.name }}/cmake-build-emsdk/bin
